class ConstNames {
  static List<String> albums = [
    "A Fifth of Beethoven",
    "America on Parade",
    "Beach Boys Vol.1",
    "Big Band Era",
    "Christmas Music Vol.1",
    "Christmas Music Vol.2",
    "Christmas Music Vol.3",
    "Classical Bach",
    "Classical Favorites Vol.1",
    "Classical Favorites Vol.2",
    "Classical Favorites Vol.3",
    "Classical Telemann Vol.1",
    "Classical Wiedoeft Vol.1",
    "Classical Wiedoeft Vol.2",
    "Classics by Mozart & Vivaldi",
    "Country Gems Vol.1",
    "Country Gems Vol.2",
    "Country Gems Vol.3",
    "Disney's Aladdin",
    "Famous Strauss Waltzes",
    "Favorite Oldies Vol.1",
    "Favorite Oldies Vol.2",
    "Favorite Oldies Vol.3",
    "Fiddle Tunes Vol.1",
    "Fiddle Tunes Vol.2",
    "Fiddler on the Roof",
    "Klezmer Collection",
    "Movie Themes Vol.1",
    "Music Man",
    "Music of Herbert Clarke",
    "New Old Favorites Vol.1",
    "New Old Favorites Vol.2",
    "New Old Favorites Vol.3",
    "Original Mills Vol.1",
    "Original Mills Vol.2",
    "Original Mills Vol.3",
    "Original Mills Vol.4",
    "Original Mills Vol.5",
    "Original Mills Vol.6",
    "Original Mills Vol.7",
    "Original Mills Vol.8",
    "Phantom of the Opera",
    "Ragtime Vol.1",
    "Rhapsody in Blue - George Gershwin",
    "Scott Joplin",
    "Semi Classical Selections Vol. 1",
    "Sinatra Favorites",
    "Snappy New Numbers Vol.1",
    "Snappy New Numbers Vol.2",
    "Songs of Yesteryear Vol.1",
    "Sound of Music",
    "Talk to the Animals",
    "The Beatles Vol.1",
    "The Beatles Vol.2",
    "Tribute to Chicago",
  ];

  static List<String> songs = [
    "Ain't Misbehavin' (40101)",
    "Air on the G String",
    "All I Ask of You",
    "All My Loving",
    "All Summer Long",
    "All That Jazz",
    "America the Beautiful",
    "American Salute",
    "And I Love Her",
    "Andante Con Moto",
    "Andante Tranquillo",
    "Arabian Nights",
    "Arkansas Traveler",
    "Artist's Life (40050)",
    "As Time Goes By",
    "Autumn Day - Scherzo",
    "Autumn In New York",
    "Ave Maria (40051)",
    "Baby Elephant Walk",
    "Barbara Ann",
    "Basin Street Blues",
    "Beale Street Blues",
    "Beautiful Ohio",
    "Beethoven's 5th Symphony",
    "Begin the Beguine",
    "Ben",
    "Big Balls in Cowtown",
    "Blue Danube Waltz (40030)",
    "Blue Skies (40130)",
    "Brandenburg Concerto #5 Movement 3 - Allegro",
    "Broadway Melody (40097)",
    "Bundle of Old Love Letters (40048)",
    "Cajun Waltz",
    "California Girls",
    "Can't Buy Me Love",
    "Can't We Be Friends (40103)",
    "Can't You Hear Me Say I Love You",
    "Caprice Viennois (40012)",
    "Carmen, Selections from",
    "Carnival of Venice,The",
    "Carolina In The Morning",
    "Charleston Baby of Mine",
    "Charmaine (40178)",
    "Chestnuts Roasting On An Open Fire",
    "Choo Choo Blues",
    "Chopin Nocturne",
    "Christmas Festival",
    "Christmas Tree Polka",
    "Class",
    "Come Fly With Me",
    "Cotton Patch",
    "Cover Me Up With Sunshine (40139)",
    "Crazy",
    "Czardas",
    "Darktown Strutter's Ball",
    "Dem Triske Rebn's Chosid'l",
    "Desert Song (40089)",
    "Devil Went Down to Georgia",
    "Diane",
    "Dill Pickle Rag",
    "Dinah (40172)",
    "Dixie and Turkey in the Straw",
    "Do You Wanna Dance",
    "Do-Re-Mi",
    "Doll Dance (40037)",
    "Dream Lover (40149)",
    "Dreamer of Dreams (40016)",
    "Dueling Banjos",
    "Easy Winners",
    "Edelweiss (40187)",
    "Edited Original Mills - # 40058",
    "Edited Original Mills - # 40059",
    "Edited Original Mills - # 40060",
    "Edited Original Mills - # 40061",
    "Edited Original Mills - # 40062",
    "Edited Original Mills - # 40063",
    "Edited Original Mills - # 40064",
    "Edited Original Mills - # 40065",
    "Edited Original Mills - # 40066",
    "Edited Original Mills - # 40067",
    "Edited Original Mills - # 40068",
    "Edited Original Mills - # 40069",
    "Edited Original Mills - # 40070",
    "Edited Original Mills - # 40071",
    "Edited Original Mills - # 40072",
    "Edited Original Mills - # 40073",
    "Edited Original Mills - # 40074",
    "Edited Original Mills - # 40075",
    "Edited Original Mills - # 40076",
    "Edited Original Mills - # 40077",
    "Edited Original Mills - # 40078",
    "Edited Original Mills - # 40079",
    "Edited Original Mills - # 40080",
    "Edited Original Mills - # 40081",
    "Edited Original Mills - # 40157",
    "Edited Original Mills - # 40158",
    "Edited Original Mills - # 40159",
    "Edited Original Mills - # 40160",
    "Edited Original Mills - # 40161",
    "Edited Original Mills - # 40162",
    "Edited Original Mills - # 40163",
    "Edited Original Mills - # 40164",
    "Edited Original Mills - # 40165",
    "Edited Original Mills - # 40166",
    "Edited Original Mills - # 40167",
    "Edited Original Mills - # 40168",
    "Eine Kleine Nachtmusik - Movement 1",
    "Eine Kleine Nachtmusik - Movement 2",
    "Eine Kleine Nachtmusik - Movement 3",
    "Eine Kleine Nachtmusik - Movement 4",
    "El Paso",
    "Elenor Rigby",
    "Felicity Rag",
    "Fidgety Feet",
    "Finale Saltarella (40056)",
    "Fire Eater",
    "Flight of the Bumble Bee",
    "Frankie and Johnnie (40019)",
    "Friend Like Me",
    "Frosty the Snowman",
    "Funiculi Funicula",
    "Gary, Indiana",
    "Ghost Riders in the Sky",
    "Girl of My Dreams (40122)",
    "Glow Worm",
    "Go U Northwestern (40090)",
    "Goodnight My Someone",
    "Grace and Beauty",
    "Grandpa's Spells Rag",
    "Gypsy Airs",
    "Gypsy Fiddles Playing",
    "Half A Moon (40175)",
    "Happy Trails",
    "Haunting Melody (40053)",
    "Heav'n Heav'n (40121)",
    "Heinzelmanchen Wachtparade",
    "Hejre Kati",
    "Heliotrope Bouquet",
    "Hello Dolly",
    "Here Comes Santa Claus",
    "High Society",
    "Hora Staccato",
    "Hungarian Dance (40009)",
    "Hungarian Rhapsody",
    "I Ain't Givin' Nothin' Away (40123)",
    "I Don't Mind Being All Alone (40142)",
    "I'm Gonna Sit Right Down and Write Myself a Letter",
    "I'm a Broken Heart Mama",
    "I've Got the Girl (40140)",
    "I've Just Seen a Face",
    "I've Lost All My Love For You (40174)",
    "If I Fell In Love",
    "If I Were a Rich Man",
    "If You Knew Susie",
    "In a Little Spanish Town (40129)",
    "It Happened in Monterey",
    "It's Beginning to Look Like Christmas",
    "Italian Concerto Movement 1 - Allegro",
    "Italian Concerto Movement 2 - Andante",
    "Italian Concerto Movement 3 - Presto",
    "Jalousie 'Tango Tzigane'",
    "Jambalia",
    "Jealous (40143)",
    "Jeannie, I Dream of Lilac Time (40132)",
    "Jingle Bell Rock",
    "Johnson Rag",
    "Joplin's New Rag",
    "Julianna",
    "Klezmer Medley",
    "Kunstler-Leben (Artist's Life)",
    "L'Abeille (40054)",
    "La Paloma (40022)",
    "La Primevera - Vivaldi",
    "Lake of Bays",
    "Largo (40126)",
    "Let It Snow",
    "Lida Rose",
    "Liebesfreud (40026)",
    "Liebesleid (40036)",
    "Lonely Goatherd",
    "Love Story",
    "Lovesick Blues",
    "Makin' Whoopee (40087)",
    "March of the Toys",
    "Marian the Librarian",
    "Martin's Waltz (Cajun Style)",
    "Matchmaker",
    "Maxwell's Silver Hammer",
    "May Day - Country Dance",
    "Mazel Tov",
    "Me and My Baby",
    "Mean To Me (40099)",
    "Meditation from Thais",
    "Medley of Southern Melodies (40131)",
    "Meet Me Tonight In Dreamland (40028)",
    "Melody in F (40330)",
    "Memphis Blues (40027)",
    "Menuette Porpora",
    "Michelle",
    "Minuet in G",
    "Minute Waltz (40283)",
    "Mister Cellophane",
    "Moon River",
    "Moonlight Serenade",
    "Music of the Night",
    "Muskrat Ramble",
    "My Blue Heaven (40083)",
    "My Dear (40098)",
    "My Fate Is In Your Hands (40091)",
    "My Favorite Things",
    "My Lady Dreams - Romanza",
    "My Sin (40136)",
    "Narcissus (new arrangement)",
    "National Emblem (40296)",
    "Night on Bald Mountain",
    "Nimble Fingers",
    "Nocturne (40033)",
    "Nola",
    "Norine Waltz",
    "Notre Dame Victory Song",
    "Now I'm In Love (40088)",
    "O Holy Night",
    "O, Divine Redeemer (40116)",
    "Ob-La-Di Ob-La-Da",
    "Old New England Moon (40092)",
    "Old Pal (40041)",
    "On Wisconsin (40100)",
    "On the Road Again",
    "One Jump Ahead",
    "One Kiss (40145)",
    "Only You and Lonely Me (40117)",
    "Orange Blossom Special (40191)",
    "Orange Blossom Special (40381)",
    "Original Hungarian Dance (40010)",
    "Original Rag",
    "Over the Waves (40084)",
    "Overture to Candide",
    "Panama",
    "Phantom of the Opera",
    "Pink Panther",
    "Polly - Song & Dance",
    "Praise Ye the Father (40138)",
    "Precious Little Thing Called Love, A (40134)",
    "Prince Ali",
    "Puff the Magic Dragon",
    "Ragtime Annie",
    "Rapscallion Rag",
    "Razzle Dazzle",
    "Red Hot Henry Brown (40035)",
    "Red River Valley",
    "Red Wing",
    "Rhapsody in Blue",
    "Rocky Top",
    "Rumanian Freilach",
    "Russian Rag",
    "SHUT-OFF",
    "Sally",
    "San Antonio Rose",
    "Sax-o-phun",
    "Saxarella",
    "Saxema",
    "Saxophobia",
    "Schon Rosmarin (40018)",
    "Second Waltz",
    "Sensation Rag",
    "Serenade (40141)",
    "Seventy Six Trombones",
    "Sextette from Lucia",
    "Silver Bells",
    "Since You Called Me Sweetheart (40047)",
    "Sinfona 'Cantata 29 No. 5' We Thank Thee, God",
    "Sixteen Going On Seventeen",
    "Skaters Waltz",
    "Sleigh Ride",
    "Snowball",
    "So Blue (40120)",
    "So Rare",
    "Solace",
    "Someday (40119)",
    "Someday Soon",
    "Sometime (40040)",
    "Somewhere My Love",
    "Song of India (new arrangement)",
    "Song of India (original)",
    "Songs of the Past (40017)",
    "Sound of Music",
    "Spread Yo' Stuff (40029)",
    "Spring Song",
    "St. Louis Blues (40086)",
    "Star Spangled Spectacular, A",
    "Stardust",
    "Starlight (40118)",
    "Stars and Stripes Forever (40309)",
    "Storm Over Oklahoma",
    "Summer Wind",
    "Sunny Side Up (40038)",
    "Sunrise, Sunset",
    "Surfer Girl",
    "Sweet Georgia Brown (new arrangement)",
    "Sweet Georgia Brown (original)",
    "Sweet Memory Waltz",
    "Sweet Wimmin (40096)",
    "Talk to the Animals",
    "Tambourin Chinois (40046)",
    "Teddy Bear's Picnic",
    "Tennessee Waltz",
    "That's A Plenty",
    "The Swan (new arrangement)",
    "The Swan (original)",
    "Theme from New York, New York",
    "Theme from The Godfather",
    "There's A Long, Long Trail A Windin'",
    "Think of Me (40300)",
    "This Is Heaven (40147)",
    "Till There Was You",
    "Tiptoes",
    "Tiroler Leid",
    "To Life",
    "Tonight You Belong To Me (40127)",
    "Tradition",
    "Trio Sonata In E Minor - Affetuoso",
    "Trio Sonata In E Minor - Allegro (1)",
    "Trio Sonata In E Minor - Allegro (2)",
    "Trio Sonata In E Minor - Grave",
    "Trio Sonata In G Minor - Allegro",
    "Trio Sonata In G Minor - Largo",
    "Trio Sonata In G Minor - Mesto",
    "Trio Sonata In G Minor - Vivace",
    "Tumbling Tumbleweed",
    "Twelfth Street Rag (40205)",
    "Valse Erica",
    "Valse Marilyn",
    "Valse Mazanetta",
    "Valse Triste (40049)",
    "Valse Vanite",
    "Voices of Spring",
    "Wabash Cannonball",
    "Walther's Prize Song",
    "Waltz I Can't Forget (40124)",
    "Waltz Llewelyn",
    "Waltz from Faust",
    "Waltzing the Blues",
    "Waves of the Danube",
    "We Need a Little Christmas",
    "We Wish You A Merry Christmas",
    "We're Loyal to You Illinois",
    "Wedding Bells Are Breaking Up That Old Gang of Mine (40125)",
    "Wells Fargo Wagon",
    "What Child Is This",
    "When I'm Sixty-Four",
    "When Summer Is Gone (40173)",
    "When You Come to the End of the Road",
    "When You're Good",
    "Where Is the Song of Songs for Me (40146)",
    "Where the Lazy Mississippi Flows",
    "White Christmas",
    "Whole New World",
    "Wien Blut (Viennese Blood)",
    "Will the Circle Be Unbroken",
    "Winter Wonderland",
    "Wishful and Blue",
    "Wishing You Were Somehow Here Again",
    "Yellow Dog Blues (40133)",
    "Yesterday (40242)",
    "You Made Me Love You",
    "You're Sixteen",
    "You've Got to Hide Your Love",
    "Your Cheatin' Heart",
    "Yours is my Heart Alone",
    "Zorba the Greek",
  ];
}
